# Company -> Category, assigned from general/public knowledge of what each
# company is known for. Only populated where confidence is reasonably high;
# left out entirely (-> blank in the workbook) wherever the company is
# unfamiliar, too diversified/conglomerate to fit one bucket, or the given
# taxonomy has no clean match (e.g. aerospace/defense primes, media,
# apparel, hospitality, chemicals, VC firms).

CATEGORY_MAP = {
    "7shifts": "Product Company",
    "ABB": "Robotics",
    "ABBYY": "AI / ML",
    "Accellor": "Consulting",
    "Accenture": "Consulting",
    "Ada": "AI / ML",
    "Adtran": "Networking",
    "AeroVironment": "Robotics",
    "Agilent": "Healthcare Tech",
    "Airbus": "",  # aerospace/defense - no clean taxonomy fit
    "AJAX": "Product Company",
    "Alan": "Healthcare Tech",
    "Alcon": "Healthcare Tech",
    "ALTEN": "Consulting",
    "Amazon": "Big Tech",
    "Amgen": "Healthcare Tech",
    "Ana Luisa": "Startup",
    "Anaplan": "Cloud",
    "Apex.AI": "AI / ML",
    "Apple": "Big Tech",
    "Applied Materials": "Semiconductor",
    "Arista Networks": "Networking",
    "Arondite": "AI / ML",
    "Arrcus": "Networking",
    "Asana": "Product Company",
    "ASM": "Semiconductor",
    "ASML": "Semiconductor",
    "AspenTech": "Product Company",
    "Astreya": "Service Company",
    "Auctane": "Product Company",
    "Autodesk": "Product Company",
    "AutoRABIT": "Product Company",
    "Avanade": "Consulting",
    "Axis": "Networking",
    "Axon": "Product Company",
    "BeyondTrust": "Cybersecurity",
    "Bio-Techne": "Healthcare Tech",
    "Blink - The Employee App": "Startup",
    "Bosch": "Automotive",
    "Cadence": "Semiconductor",
    "Cambridge Consultants": "Consulting",
    "Candescent": "FinTech",
    "Canonical": "Cloud",
    "Capital One": "FinTech",
    "Careerswift": "Startup",
    "Centific": "AI / ML",
    "Checkout.com": "FinTech",
    "Ciena": "Networking",
    "Clio": "Product Company",
    "CloudSEK": "Indian Product",
    "CME Group": "FinTech",
    "ComplyAdvantage": "FinTech",
    "ConnectWise": "Product Company",
    "Coveo": "AI / ML",
    "Creatify": "AI / ML",
    "Dashlane": "Cybersecurity",
    "Despegar": "Product Company",
    "Deutsche Bank": "FinTech",
    "Devsinc": "Service Company",
    "Dexmate": "Robotics",
    "DoubleVerify": "Product Company",
    "DRW": "FinTech",
    "Duolingo": "Product Company",
    "DXC Technology": "Service Company",
    "Edwards Lifesciences": "Healthcare Tech",
    "Ellation": "Product Company",
    "Elwood": "FinTech",
    "Empower": "FinTech",
    "Endava": "Service Company",
    "Everfox": "Cybersecurity",
    "Exadel": "Service Company",
    "Faros": "AI / ML",
    "Feathery": "Startup",
    "Fermi AI": "AI / ML",
    "Fever": "Product Company",
    "Fidelity Investments": "FinTech",
    "FINN": "Automotive",
    "Five9": "Cloud",
    "Flexport": "Product Company",
    "Formlabs": "Product Company",
    "Foundation AI": "AI / ML",
    "G-Research": "FinTech",
    "GDIT": "Government",
    "GE HealthCare": "Healthcare Tech",
    "Gentex": "Automotive",
    "GeoComply": "Cybersecurity",
    "General Dynamics Mission Systems": "Government",
    "Global Payments": "FinTech",
    "GlobalFoundries": "Semiconductor",
    "Google": "Big Tech",
    "GoVenti": "Automotive",
    "Grab": "Product Company",
    "Graphcore": "Semiconductor, AI / ML",
    "GSA": "FinTech",
    "Guidewire": "Product Company",
    "Harmattan AI": "AI / ML",
    "Hewlett Packard Enterprise": "Cloud",
    "Highstreet IT Solutions": "Service Company",
    "Hong Leong Bank": "FinTech",
    "ICONIQ Capital": "FinTech",
    "Infobip": "Cloud",
    "Informed Solutions": "Service Company",
    "Integer": "Healthcare Tech",
    "Intel": "Semiconductor",
    "Invesco": "FinTech",
    "IXL Learning": "Product Company",
    "Johnson & Johnson": "Healthcare Tech",
    "Julius Baer": "FinTech",
    "Jump Trading": "FinTech",
    "Kabam": "Gaming",
    "Kinaxis": "Cloud",
    "KINEXON": "Startup",
    "KLA": "Semiconductor",
    "Konrad": "Service Company",
    "Kyndryl": "Service Company",
    "Later": "Product Company",
    "Leidos": "Government",
    "LexisNexis Risk Solutions": "Product Company",
    "Logicalis": "Service Company",
    "Logitech": "Product Company",
    "LSEG": "FinTech",
    "Magical": "AI / ML",
    "Magna": "Automotive",
    "Magnet Forensics": "Cybersecurity",
    "Manulife": "FinTech",
    "Mapbox": "Product Company",
    "Marsh McLennan": "Consulting",
    "Marvell": "Semiconductor",
    "MasterBorn": "Service Company",
    "Megaport": "Networking",
    "Meshy": "AI / ML",
    "Microsoft": "Big Tech",
    "Mistral AI": "AI / ML",
    "MKS": "Semiconductor",
    "Moloco": "AI / ML",
    "Moog": "Robotics",
    "Morgan Stanley": "FinTech",
    "Motorola Solutions": "Product Company",
    "mthree": "Service Company",
    "NAV CANADA": "Government",
    "NETGEAR": "Networking",
    "Netomi": "AI / ML",
    "Neura Robotics": "Robotics",
    "NIH-NCBI": "Government",
    "NVIDIA": "Semiconductor, AI / ML",
    "NXP Semiconductors": "Semiconductor",
    "OfferUp": "Product Company",
    "OMP": "Cloud",
    "OPSWAT": "Cybersecurity",
    "Opus 2": "Product Company",
    "Orion Health": "Healthcare Tech",
    "Outset Medical": "Healthcare Tech",
    "Packmatic": "Startup",
    "Palantir": "AI / ML",
    "Pave Bank": "FinTech",
    "Payoneer": "FinTech",
    "Peak": "Gaming",
    "Perplexity": "AI / ML",
    "Pfizer": "Healthcare Tech",
    "Philips": "Healthcare Tech",
    "Pitney Bowes": "Product Company",
    "Plane Software": "Product Company",
    "Plexus": "Service Company",
    "PolicyMe": "FinTech",
    "Priceline": "Product Company",
    "Provenir": "FinTech",
    "PwC": "Consulting",
    "Quality Consulting Group": "Consulting",
    "Qualtrics": "Cloud",
    "Red Hat": "Cloud",
    "RELX": "Product Company",
    "ReversingLabs": "Cybersecurity",
    "Rivian": "Automotive",
    "Robert Half": "Service Company",
    "Rocket Software": "Product Company",
    "Rockwell Automation": "Robotics",
    "RSM": "Consulting",
    "Sabre": "Cloud",
    "SAP Fioneer": "FinTech",
    "Scott Logic": "Consulting",
    "Semtech": "Semiconductor",
    "SentinelOne": "Cybersecurity",
    "Shift Technologies": "AI / ML",
    "Signify": "Product Company",
    "Snowflake": "Cloud",
    "SolarWinds": "Cloud",
    "Sonar": "Product Company",
    "Spacial AI": "AI / ML",
    "SpotOn": "FinTech",
    "Stack Builders": "Service Company",
    "State Street": "FinTech",
    "Stripe": "FinTech",
    "Super.com": "Product Company",
    "Susquehanna International Group": "FinTech",
    "Symphony Solutions": "Service Company",
    "Taboola": "Product Company",
    "Taktile": "FinTech",
    "TD Bank": "FinTech",
    "Tekion": "Automotive",
    "Telnyx": "Cloud",
    "TELUS Digital": "Service Company",
    "Tencent": "Big Tech",
    "Teya": "FinTech",
    "Thales": "Government",
    "Thermo Fisher Scientific": "Healthcare Tech",
    "Thoughtworks": "Consulting",
    "TikTok": "Big Tech",
    "Toast": "Cloud",
    "TomTom": "Product Company",
    "Too Good To Go": "Startup",
    "Travelers": "FinTech",
    "TribalScale": "Service Company",
    "Tricentis": "Cloud",
    "Trimble": "Product Company",
    "Tripadvisor": "Product Company",
    "UiPath": "AI / ML",
    "USAA": "FinTech",
    "Valeo": "Automotive",
    "Valtech": "Consulting",
    "Wallapop": "Product Company",
    "WATI.io": "Cloud",
    "WeRide.ai": "Automotive",
    "WindBorne Systems": "Startup",
    "Wingtra AG": "Robotics",
    "Wolters Kluwer": "Product Company",
    "Yellowbrick Data": "Cloud",
    "Yotpo": "Product Company",
}
