# Verified via WebSearch/WebFetch (session date: July 2026). Only pages that
# were actually found/confirmed are included; anything not confidently
# verified is left blank rather than guessed.
# Each entry: website, careers, internship, new_grad (empty string = blank)

COMPANY_LINKS = {
    "Google": {
        "website": "https://www.google.com",
        "careers": "https://careers.google.com/",
        "internship": "https://www.google.com/about/careers/applications/students/",
        "new_grad": "https://www.google.com/about/careers/applications/students/",
    },
    "Amazon": {
        "website": "https://www.amazon.com",
        "careers": "https://www.amazon.jobs",
        "internship": "https://www.amazon.jobs/content/en/career-programs/university/internships-for-students",
        "new_grad": "https://www.amazon.jobs/content/en/career-programs/university/jobs-for-grads",
    },
    "Microsoft": {
        "website": "https://www.microsoft.com",
        "careers": "https://careers.microsoft.com",
        "internship": "https://careers.microsoft.com/v2/global/en/universityinternship",
        "new_grad": "https://careers.microsoft.com/v2/global/en/students",
    },
    "Apple": {
        "website": "https://www.apple.com",
        "careers": "https://jobs.apple.com",
        "internship": "https://www.apple.com/careers/us/work-at-apple/students.html",
        "new_grad": "https://www.apple.com/careers/us/work-at-apple/students.html",
    },
    "TikTok": {
        "website": "https://www.tiktok.com",
        "careers": "https://lifeattiktok.com",
        "internship": "https://lifeattiktok.com/university",
        "new_grad": "https://lifeattiktok.com/university",
    },
    "NVIDIA": {
        "website": "https://www.nvidia.com",
        "careers": "https://www.nvidia.com/en-us/about-nvidia/careers/",
        "internship": "https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/",
        "new_grad": "https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/",
    },
    "Intel": {
        "website": "https://www.intel.com",
        "careers": "https://www.intel.com/content/www/us/en/jobs/hiring.html",
        "internship": "",
        "new_grad": "",
    },
    "Stripe": {
        "website": "https://stripe.com",
        "careers": "https://stripe.com/jobs",
        "internship": "https://stripe.com/jobs/university",
        "new_grad": "https://stripe.com/jobs/university",
    },
    "Rivian": {
        "website": "https://rivian.com",
        "careers": "https://careers.rivian.com",
        "internship": "https://careers.rivian.com/students",
        "new_grad": "https://careers.rivian.com/students",
    },
    "Palantir": {
        "website": "https://www.palantir.com",
        "careers": "https://jobs.lever.co/palantir",
        "internship": "",
        "new_grad": "",
    },
    "Snowflake": {
        "website": "https://www.snowflake.com",
        "careers": "https://careers.snowflake.com/us/en",
        "internship": "https://careers.snowflake.com/us/en/university",
        "new_grad": "https://careers.snowflake.com/us/en/university",
    },
    "Red Hat": {
        "website": "https://www.redhat.com",
        "careers": "https://www.redhat.com/en/jobs",
        "internship": "",
        "new_grad": "",
    },
    "Canonical": {
        "website": "https://canonical.com",
        "careers": "https://canonical.com/careers",
        "internship": "",
        "new_grad": "",
    },
    "Hewlett Packard Enterprise": {
        "website": "https://www.hpe.com",
        "careers": "https://careers.hpe.com/us/en",
        "internship": "https://careers.hpe.com/us/en/hpe-interns",
        "new_grad": "https://careers.hpe.com/us/en/students",
    },
    "UiPath": {
        "website": "https://www.uipath.com",
        "careers": "https://www.uipath.com/careers",
        "internship": "",
        "new_grad": "",
    },
    "Mistral AI": {
        "website": "https://mistral.ai",
        "careers": "https://mistral.ai/careers/",
        "internship": "",
        "new_grad": "",
    },
    "Perplexity": {
        "website": "https://www.perplexity.ai",
        "careers": "https://www.perplexity.ai/hub/careers",
        "internship": "",
        "new_grad": "",
    },
    "Duolingo": {
        "website": "https://www.duolingo.com",
        "careers": "https://careers.duolingo.com",
        "internship": "",
        "new_grad": "https://careers.duolingo.com/?type=New+Grad",
    },
    "Toast": {
        "website": "https://www.toasttab.com",
        "careers": "https://careers.toasttab.com",
        "internship": "https://careers.toasttab.com/early-career",
        "new_grad": "https://careers.toasttab.com/early-career",
    },
    "Grab": {
        "website": "https://www.grab.com",
        "careers": "https://www.grab.careers/en/",
        "internship": "https://www.grab.careers/en/teams/internships/",
        "new_grad": "https://www.grab.careers/en/teams/internships/",
    },
    "Marvell": {
        "website": "https://www.marvell.com",
        "careers": "https://www.marvell.com/company/careers.html",
        "internship": "https://www.marvell.com/company/careers/university-recruiting.html",
        "new_grad": "https://www.marvell.com/company/careers/university-recruiting.html",
    },
    "NXP Semiconductors": {
        "website": "https://www.nxp.com",
        "careers": "https://www.nxp.com/company/about-nxp/careers:CAREERS",
        "internship": "https://www.nxp.com/company/about-nxp/our-team-members/future-talent:FUTURE-TALENT",
        "new_grad": "https://www.nxp.com/company/about-nxp/our-team-members/future-talent:FUTURE-TALENT",
    },
    "ASML": {
        "website": "https://www.asml.com",
        "careers": "https://www.asml.com/en/careers",
        "internship": "https://www.asml.com/en/careers/students-new-graduates/us/internships",
        "new_grad": "https://www.asml.com/en/careers/students-new-graduates/programs-for-graduates",
    },
    "Applied Materials": {
        "website": "https://www.appliedmaterials.com",
        "careers": "https://www.appliedmaterials.com/us/en/careers.html",
        "internship": "https://www.appliedmaterials.com/us/en/careers/internship-program.html",
        "new_grad": "https://www.appliedmaterials.com/us/en/careers/students-early-career.html",
    },
    "GlobalFoundries": {
        "website": "https://gf.com",
        "careers": "https://gf.com/careers/",
        "internship": "https://gf.com/careers/internships-at-gf/",
        "new_grad": "https://gf.com/careers/early-career/",
    },
    "KLA": {
        "website": "https://www.kla.com",
        "careers": "https://www.kla.com/careers",
        "internship": "https://www.kla.com/careers/emerging-talent",
        "new_grad": "https://www.kla.com/careers/emerging-talent",
    },
    "Cadence": {
        "website": "https://www.cadence.com",
        "careers": "https://www.cadence.com/en_US/home/company/life-at-cadence/careers.html",
        "internship": "https://www.cadence.com/en_US/home/company/careers/interns-and-new-grads.html",
        "new_grad": "https://www.cadence.com/en_US/home/company/careers/interns-and-new-grads.html",
    },
    "Boeing": {
        "website": "https://www.boeing.com",
        "careers": "https://jobs.boeing.com",
        "internship": "https://jobs.boeing.com/internships",
        "new_grad": "https://jobs.boeing.com/entry-level",
    },
    "Philips": {
        "website": "https://www.philips.com",
        "careers": "https://www.careers.philips.com",
        "internship": "https://www.careers.philips.com/student/global/en/internships-apprenticeship",
        "new_grad": "https://www.careers.philips.com/student/global/en",
    },
    "Bosch": {
        "website": "https://www.bosch.com",
        "careers": "https://www.bosch.com/careers/",
        "internship": "",
        "new_grad": "https://www.bosch.com/careers/career-opportunities/junior-managers-program/",
    },
    "Ciena": {
        "website": "https://www.ciena.com",
        "careers": "https://www.ciena.com/careers",
        "internship": "https://www.ciena.com/careers/students-new-graduates",
        "new_grad": "https://www.ciena.com/careers/students-new-graduates",
    },
    "Motorola Solutions": {
        "website": "https://www.motorolasolutions.com",
        "careers": "https://www.motorolasolutions.com/en_us/about/careers.html",
        "internship": "",
        "new_grad": "",
    },
    "Tencent": {
        "website": "https://www.tencent.com",
        "careers": "https://careers.tencent.com/en-us/home.html",
        "internship": "https://careers.tencent.com/en-us/campusrecruit.html",
        "new_grad": "https://careers.tencent.com/en-us/campusrecruit.html",
    },
    "RELX": {
        "website": "https://www.relx.com",
        "careers": "https://www.relx.com/careers",
        "internship": "https://www.relx.com/careers/graduates-and-early-careers",
        "new_grad": "https://www.relx.com/careers/graduates-and-early-careers",
    },
    "Checkout.com": {
        "website": "https://www.checkout.com",
        "careers": "https://www.checkout.com/careers",
        "internship": "",
        "new_grad": "",
    },
    "DXC Technology": {
        "website": "https://dxc.com",
        "careers": "https://careers.dxc.com",
        "internship": "https://careers.dxc.com/global/en/c/internship-jobs",
        "new_grad": "",
    },
    "Accenture": {
        "website": "https://www.accenture.com",
        "careers": "https://www.accenture.com/us-en/careers",
        "internship": "https://www.accenture.com/us-en/careers/life-at-accenture/internships-students",
        "new_grad": "https://www.accenture.com/gb-en/careers/life-at-accenture/entry-level",
    },
    "Avanade": {
        "website": "https://www.avanade.com",
        "careers": "https://www.avanade.com/en-us/career",
        "internship": "https://www.avanade.com/en/careers/your-career/graduates",
        "new_grad": "https://www.avanade.com/en/careers/your-career/graduates",
    },
    "Thoughtworks": {
        "website": "https://www.thoughtworks.com",
        "careers": "https://www.thoughtworks.com/careers",
        "internship": "",
        "new_grad": "https://www.thoughtworks.com/en-in/careers/graduates",
    },
    "PwC": {
        "website": "https://www.pwc.com",
        "careers": "https://www.pwc.com/us/en/careers/entry-level/recruiting.html",
        "internship": "https://www.pwc.com/us/en/careers/entry-level/internships.html",
        "new_grad": "",
    },
    "Leidos": {
        "website": "https://www.leidos.com",
        "careers": "https://careers.leidos.com",
        "internship": "https://careers.leidos.com/pages/intern-jobs",
        "new_grad": "https://careers.leidos.com/pages/new-graduate-jobs",
    },
    "GDIT": {
        "website": "https://www.gdit.com",
        "careers": "https://www.gdit.com/careers/",
        "internship": "https://www.gdit.com/careers/featured-career-stages/early-talent-and-internships/",
        "new_grad": "https://www.gdit.com/careers/featured-career-stages/early-talent-and-internships/",
    },
    "Capital One": {
        "website": "https://www.capitalone.com",
        "careers": "https://www.capitalonecareers.com",
        "internship": "https://www.capitalonecareers.com/internship-programs",
        "new_grad": "https://www.capitalonecareers.com/graduate-programs",
    },
    "Morgan Stanley": {
        "website": "https://www.morganstanley.com",
        "careers": "https://www.morganstanley.com/people",
        "internship": "https://www.morganstanley.com/people-opportunities/students-graduates",
        "new_grad": "https://www.morganstanley.com/people-opportunities/students-graduates",
    },
    "Deutsche Bank": {
        "website": "https://www.db.com",
        "careers": "https://careers.db.com",
        "internship": "https://careers.db.com/students-graduates/internship-programme/",
        "new_grad": "https://careers.db.com/students-graduates/graduate-programme/",
    },
    "Fidelity Investments": {
        "website": "https://www.fidelity.com",
        "careers": "https://jobs.fidelity.com/en/",
        "internship": "https://jobs.fidelity.com/en/students/internships/",
        "new_grad": "https://jobs.fidelity.com/en/students/entry-level-roles/",
    },
    "Susquehanna International Group": {
        "website": "https://sig.com",
        "careers": "https://careers.sig.com/jobs",
        "internship": "https://careers.sig.com/intern-co-op/jobs",
        "new_grad": "https://careers.sig.com/us-campus",
    },
    "Jump Trading": {
        "website": "https://www.jumptrading.com",
        "careers": "https://www.jumptrading.com/careers",
        "internship": "https://www.jumptrading.com/hr/students-new-grads",
        "new_grad": "https://www.jumptrading.com/hr/students-new-grads",
    },
    "DRW": {
        "website": "https://drw.com",
        "careers": "https://www.drw.com/work-at-drw",
        "internship": "https://www.drw.com/work-at-drw/interns",
        "new_grad": "https://www.drw.com/work-at-drw/graduates",
    },
    "G-Research": {
        "website": "https://www.gresearch.com",
        "careers": "https://www.gresearch.com/vacancies/",
        "internship": "https://www.gresearch.com/students-graduates/graduates/",
        "new_grad": "https://www.gresearch.com/students-graduates/graduates/",
    },
}
